; BLE WiFi Provisioner - ESP32-S3
; Waveshare ESP32-S3-LCD-1.47B

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Use huge_app partition for BLE + WiFi
board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3

lib_extra_dirs =
    ../../libs

lib_deps =
    https://github.com/lovyan03/LovyanGFX.git#develop
